/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproye2;

import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian Laverde
 */
public class Agregar_Candi extends javax.swing.JFrame {

    String candi[][];
    int fila;
    int cod;
    public Agregar_Candi(String candi[][], int fila, int cod) {
        initComponents();
        this.candi = candi;
        this.fila = fila;
        this.cod = cod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtCedula = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jcCiudad = new javax.swing.JComboBox<>();
        jcPoliticos = new javax.swing.JComboBox<>();
        jrIzquierda = new javax.swing.JRadioButton();
        jrDere = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(380, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar candidato");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 23, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Numero de cedula: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ciudad de origen:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Partido politico:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 218, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ideologia politica:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 275, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Propuestas:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        getContentPane().add(jtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 140, 30));

        jtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtNombre.setPreferredSize(new java.awt.Dimension(4, 21));
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 140, 30));

        jcCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 140, 30));

        jcPoliticos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcPoliticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 140, 30));

        jrIzquierda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrIzquierda.setText("Izquierda");
        getContentPane().add(jrIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jrDere.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrDere.setText("Derecha");
        getContentPane().add(jrDere, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setText("Salir");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 70, -1));

        btnAgregar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar1.setText("Agregar candidato");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        crear(candi, fila, cod);
        dispose();
        
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jcCiudad;
    private javax.swing.JComboBox<String> jcPoliticos;
    private javax.swing.JRadioButton jrDere;
    private javax.swing.JRadioButton jrIzquierda;
    private javax.swing.JTextField jtCedula;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables


    public void crear(String can[][], int fila, int co){
        String nombre = jtNombre.getText();
        String cedula = jtCedula.getText();
        String ciudad = ""+jcCiudad.getSelectedItem();
        String politica = ""+jcPoliticos.getSelectedItem();
        int ideo = 0;
        if(jrIzquierda.isSelected()){
            ideo = 0;
        }else if(jrDere.isSelected()){
            ideo = 1;
        }
        can[fila][0] = ""+co;
        can[fila][1] = nombre;
        can[fila][2] = cedula;
        can[fila][3] = ciudad;
        can[fila][4] = politica;
        can[fila][5] = ""+ideo;
        JOptionPane.showMessageDialog(null, "Usuario creado");
        fila++;
        co++;
        this.fila = fila;
        this.candi = can;
        this.cod = co;
    }
    
}
